### ISSUE TITLE
Push failed

### ISSUE THREAD

**Issue by David263** [grayghostvisuals/practice-git#115]
I was successful in cloning and pulling these files, but pushing from Windows failed. No idea why.

I'm following the tutorial at https://www.youtube.com/watch?v=HVsySz-h9r4 .

C:\Web\Tests\git-practice>git push origin master
remote: Permission to grayghostvisuals/practice-git.git denied to David263.
fatal: unable to access 'https://github.com/grayghostvisuals/practice-git/': The requested URL returned error: 403

**Comment by David263** [comment]
Is anyone there?

**Comment by grayghostvisuals** [comment]
@David263 That's because you don't have admin privileges to push to this repo. You can only push to your forked copy. If you want to submit code to this repo you'll have to do so through a pull request.
