### ISSUE TITLE
missing step in the pizza_recipe.txt

### ISSUE THREAD

**Issue by mkienzle** [grayghostvisuals/practice-git#30]
Hi,

I find there is a missing step in the pizza_recipe.txt, a bug I have a fix for. 

Would you let me submit it ?

cheers,
marco

**Comment by grayghostvisuals** [comment]
yup. Already merged :metal:

**Comment by grayghostvisuals** [comment]
FYI: For your commit msg you can say something like:

> Adds final recipe line. closes #30.

Typing “closes #30” will in turn close the issue it references automagically!
