### ISSUE TITLE
testerdietestest

### ISSUE THREAD

**Issue by EleonoraSmid** [grayghostvisuals/practice-git#41]
#40 
Creating a test reference to this reaction. 

:p

**Comment by grayghostvisuals** [comment]
Boom! :beers: :bee: 

A screenshot of the process on my end.

![screenshot 2016-03-23 19 44 02](https://cloud.githubusercontent.com/assets/934322/14004333/a1b9dfda-f12f-11e5-9380-217cb1888cfc.png)
